platform :ios, '7.0'

target 'LotusConnect' do
    pod 'LayerKit'
    pod 'Atlas'
    pod 'Parse'
    pod 'ParseUI'
    pod 'SVProgressHUD'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
end

